# Generated by Django 4.1 on 2023-10-03 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0006_fotografia_usuario_fotografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='usuario_fotografia',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
